alter table cars add constraint FK1itgarrpxn99j57gfqhlotuel
    foreign key (price_id) references price_list (price_id);
alter table cars add constraint FKcki51tfk2udss8oujqvpu1mpj
    foreign key (car_type_id) references car_type (car_type_id);
alter table orders add constraint FKd2p23ixwrrt395glgi9nnbj23
    foreign key (car_id) references cars (car_id);
alter table orders add constraint FKpxtb8awmi0dk6smoh2vp1litg
        foreign key (customer_id) references customers (customer_id);
alter table user_roles add constraint FK55itppkw3i07do3h7qoclqd4k
    foreign key (user_id) references user (user_id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6
    foreign key (role_id) references roles (role_id);