version: '3.7'
services:
  postgres-autoshop:
    container_name: postgres-autoshop
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auto_project
  autoshop:
    container_name: autoshop
    image: autoshop
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-autoshop:5432/auto_project
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSOWRD: password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres-autoshop